CREATE TABLE `Company` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,

    `Name` VARCHAR(150) NOT NULL,
    `Document` VARCHAR(14) NOT NULL,
    `Description` TEXT NULL,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_Company` PRIMARY KEY (`Id`),
    CONSTRAINT `UK_Company_Document` UNIQUE (`Document`)
);