CREATE TABLE `User` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CompanyId` INT UNSIGNED NOT NULL,

    `Name` VARCHAR(150) NOT NULL,
    `Email` VARCHAR(255) NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
    `HashedRefreshToken` VARCHAR(255) NULL,
    `PasswordResetToken` VARCHAR(255) NULL,
    `IsFirstAccess` BOOLEAN NOT NULL DEFAULT TRUE,
    `IsSystemRoot` BOOLEAN NOT NULL DEFAULT FALSE,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_User` PRIMARY KEY (`Id`),
    CONSTRAINT `UK_User_Email` UNIQUE (`Email`),

    CONSTRAINT `FK_User_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
);