CREATE TABLE `Batch` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CompanyId` INT UNSIGNED NOT NULL,

    `Name` VARCHAR(150) NOT NULL,
    `StartsAt` DATETIME(3) NOT NULL,
    `EndsAt` DATETIME(3) NOT NULL,

    `Status` ENUM('SCHEDULED', 'RUNNING', 'CANCELLED', 'FINISHED', 'FAILED') NOT NULL DEFAULT 'SCHEDULED',

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_Batch` PRIMARY KEY (`Id`),

    CONSTRAINT `FK_Batch_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
);
