-- CREATE TABLE `Company` (
--     `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,

--     `Name` VARCHAR(150) NOT NULL,
--     `Document` VARCHAR(14) NOT NULL,
--     `Description` TEXT NULL,

--     `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
--     `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
--     `DeletedAt` DATETIME(3) NULL,

--     CONSTRAINT `PK_Company` PRIMARY KEY (`Id`),
--     CONSTRAINT `UK_Company_Document` UNIQUE (`Document`)
-- );

-- CREATE TABLE `User` (
--     `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     `CompanyId` INT UNSIGNED NOT NULL,

--     `Name` VARCHAR(150) NOT NULL,
--     `Email` VARCHAR(50) NOT NULL,
--     `Password` VARCHAR(255) NOT NULL,
--     `HashedRefreshToken` VARCHAR(255) NULL,
--     `PasswordResetToken` VARCHAR(255) NULL,
--     `IsFirstAccess` BOOLEAN NOT NULL DEFAULT TRUE,
--     `IsSystemRoot` BOOLEAN NOT NULL DEFAULT FALSE,

--     `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
--     `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
--     `DeletedAt` DATETIME(3) NULL,

--     CONSTRAINT `PK_User` PRIMARY KEY (`Id`),
--     CONSTRAINT `UK_User_CompanyId_Email` UNIQUE (`CompanyId`, `Email`),

--     CONSTRAINT `FK_User_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
-- );

-- CREATE TABLE `List` (
--     `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     `CompanyId` INT UNSIGNED NOT NULL,

--     `Name` VARCHAR(150) NOT NULL,
--     `Subject` VARCHAR(255) NOT NULL,
--     `Color` VARCHAR(7) NOT NULL,

--     `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
--     `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
--     `DeletedAt` DATETIME(3) NULL,

--     CONSTRAINT `PK_List` PRIMARY KEY (`Id`),
--     CONSTRAINT `UK_List_CompanyId_Name` UNIQUE (`CompanyId`, `Name`),

--     CONSTRAINT `FK_List_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
-- );

-- CREATE TABLE `Contact` (
--     `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     `CompanyId` INT UNSIGNED NOT NULL,
--     `ListId` INT UNSIGNED NOT NULL,

--     `Name` VARCHAR(150) NOT NULL,
--     `Phone` VARCHAR(20) NOT NULL,
--     `Active` BOOLEAN NOT NULL DEFAULT TRUE,

--     `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
--     `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
--     `DeletedAt` DATETIME(3) NULL,

--     CONSTRAINT `PK_Contact` PRIMARY KEY (`Id`),
--     CONSTRAINT `UK_Contact_CompanyId_Phone` UNIQUE (`CompanyId`, `Phone`),

--     CONSTRAINT `FK_Contact_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
--     CONSTRAINT `FK_Contact_ListId` FOREIGN KEY (`ListId`) REFERENCES `List` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,

--     INDEX `IX_Contact_Company_List` (`CompanyId`, `ListId`)
-- );

-- CREATE TABLE `Template` (
--     `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
--     `CompanyId` INT UNSIGNED NOT NULL,

--     `Name` VARCHAR(150) NOT NULL,
--     `Content` JSON NOT NULL,

--     `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
--     `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
--     `DeletedAt` DATETIME(3) NULL,

--     CONSTRAINT `PK_Template` PRIMARY KEY (`Id`),
--     CONSTRAINT `UK_Template_CompanyId_Name` UNIQUE (`CompanyId`, `Name`),

--     CONSTRAINT `FK_Template_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
-- );

CREATE TABLE `Batch` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CompanyId` INT UNSIGNED NOT NULL,

    `Name` VARCHAR(150) NOT NULL,
    `StartedAt` DATETIME(3) NULL,
    `EndedAt` DATETIME(3) NULL,

    `Status` ENUM("PENDING", "RUNNING", "CANCELLED", "FINISHED", "FAILED", "PARTIAL") NOT NULL DEFAULT "PENDING",

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_Batch` PRIMARY KEY (`Id`),

    CONSTRAINT `FK_Batch_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `BatchSend` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CompanyId` INT UNSIGNED NOT NULL,
    `BatchId` INT UNSIGNED NOT NULL,
    `ContactId` INT UNSIGNED NOT NULL,
    `TemplateId` INT UNSIGNED NOT NULL,

    `TemplateSnapshot` JSON NOT NULL,

    `Status` ENUM("WAITING", "PROCESSING", "SENT", "DELIVERED", "READ", "FAILED") NOT NULL DEFAULT "WAITING",

    `Attempts` INT UNSIGNED NOT NULL DEFAULT 0,
    `ErrorCode` VARCHAR(100) NULL,
    `ErrorMessage` VARCHAR(1000) NULL,

    `ScheduledAt` DATETIME(3) NULL,
    `StartedAt`   DATETIME(3) NULL,
    `CompletedAt`  DATETIME(3) NULL,

    `MessageId` VARCHAR(255) NULL,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    CONSTRAINT `PK_BatchSend` PRIMARY KEY (`Id`),
    CONSTRAINT `UK_BatchSend_BatchId_ContactId` UNIQUE (`BatchId`, `ContactId`),

    CONSTRAINT `FK_BatchSend_BatchId` FOREIGN KEY (`BatchId`) REFERENCES `Batch` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_BatchSend_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_BatchSend_ContactId` FOREIGN KEY (`ContactId`) REFERENCES `Contact` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_BatchSend_TemplateId` FOREIGN KEY (`TemplateId`) REFERENCES `Template` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,

    INDEX `IX_BatchSend_Company_Status` (`CompanyId`, `Status`)
);
