-- DONE
CREATE TABLE `Company` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,

    `Name` VARCHAR(150) NOT NULL,
    `Document` VARCHAR(14) NOT NULL,
    `Description` TEXT NULL,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_Company` PRIMARY KEY (`Id`),
    CONSTRAINT `UK_Company_Document` UNIQUE (`Document`)
);

-- DONE
CREATE TABLE `User` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CompanyId` INT UNSIGNED NOT NULL,

    `Name` VARCHAR(150) NOT NULL,
    `Email` VARCHAR(255) NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
    `HashedRefreshToken` VARCHAR(255) NULL,
    `PasswordResetToken` VARCHAR(255) NULL,
    `IsFirstAccess` BOOLEAN NOT NULL DEFAULT TRUE,
    `IsSystemRoot` BOOLEAN NOT NULL DEFAULT FALSE,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_User` PRIMARY KEY (`Id`),
    CONSTRAINT `UK_User_Email` UNIQUE (`Email`),

    CONSTRAINT `FK_User_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `List` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CompanyId` INT UNSIGNED NOT NULL,

    `Name` VARCHAR(150) NOT NULL,
    `Subject` VARCHAR(255) NOT NULL,
    `Color` VARCHAR(7) NOT NULL,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_List` PRIMARY KEY (`Id`),

    CONSTRAINT `FK_List_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `Contact` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CompanyId` INT UNSIGNED NOT NULL,
    `ListId` INT UNSIGNED NOT NULL,

    `Name` VARCHAR(150) NOT NULL,
    `Phone` VARCHAR(20) NOT NULL,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_Contact` PRIMARY KEY (`Id`),
    CONSTRAINT `UK_Contact_Phone` UNIQUE (`Phone`),

    CONSTRAINT `FK_Contact_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_Contact_ListId` FOREIGN KEY (`ListId`) REFERENCES `List` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `Note` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ContactId` INT UNSIGNED NOT NULL,

    `Content` TEXT NOT NULL,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_Note` PRIMARY KEY (`Id`),

    CONSTRAINT `FK_Note_ContactId` FOREIGN KEY (`ContactId`) REFERENCES `Contact` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
);