CREATE TABLE `List` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `CompanyId` INT UNSIGNED NOT NULL,

    `Name` VARCHAR(150) NOT NULL,
    `Subject` VARCHAR(255) NOT NULL,
    `Color` VARCHAR(7) NOT NULL,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_List` PRIMARY KEY (`Id`),

    CONSTRAINT `FK_List_CompanyId` FOREIGN KEY (`CompanyId`) REFERENCES `Company` (`Id`) ON DELETE RESTRICT ON UPDATE CASCADE
);