CREATE TABLE `Note` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ContactId` INT UNSIGNED NOT NULL,

    `Observation` TEXT NOT NULL,

    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `DeletedAt` DATETIME(3) NULL,

    CONSTRAINT `PK_Note` PRIMARY KEY (`Id`),

    CONSTRAINT `FK_Note_ContactId` FOREIGN KEY (`ContactId`) REFERENCES `Contact` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE
);